#!/usr/bin/bash

echo "::group:: ===$(basename "$0")==="

set -eoux pipefail

# Put the Amethystora artwork where the boot menu, the boot splash, GDM and the Logo Menu look for it.
# The artwork itself lives in system_files/shared and is generated by branding/generate.mjs.

# Boot menu: GRUB reads its own bitmap font format, so the Inter that theme.txt asks for is built
# here from the TTF the image already ships for the boot splash. GRUB looks the font up by the name
# stored in the file, which grub2-mkfont always writes as "<family> <style> <size>" — for a regular
# face, "<family> Regular 16". The family is given here instead of being taken from the TTF, whose
# own family name is "Inter 18pt" in some Inter releases and would stop matching theme.txt.
GRUB_THEME_DIR=/usr/share/grub/themes/amethystora
GRUB_FONT_NAME="Inter Regular 16"
grub2-mkfont --size=16 --name="Inter" \
    --output="${GRUB_THEME_DIR}/font16.pf2" /usr/share/fonts/rsms-inter-fonts/Inter-Regular.ttf
test -s "${GRUB_THEME_DIR}/font16.pf2"
# The name in the font file and the name theme.txt asks for have to be the same string, or the menu
# silently falls back to GRUB's own font
grep -aq "${GRUB_FONT_NAME}" "${GRUB_THEME_DIR}/font16.pf2"
grep -qE "^[[:space:]]*item_font = \"${GRUB_FONT_NAME}\"$" "${GRUB_THEME_DIR}/theme.txt"

# Boot splash: the Amethystora theme runs on the script plugin (amethystora.script and its images, from
# branding/generate.mjs). Its Font= lines are not read by the plugin but make dracut put Inter in the initramfs.
# 19-initramfs.sh bakes the selected theme into the initramfs.
plymouth-set-default-theme amethystora

# Logos under Fedora's own file names, which build.sh takes away with fedora-logos. The names cannot
# be changed: they are where GDM, the Settings About page (gnome-control-center is built with the path
# baked in) and Fedora's fallback boot splash look. The Amethystora pictures are installed there.
declare -A UPSTREAM_ARTWORK=(
    # The login screen, which draws on a dark background: the wordmark with the dark lettering
    # disappears into it and leaves the gem on its own. The lit variant, matching the stone the boot
    # splash hands over still glowing. zz1-amethystora-modifications names the same file directly as
    # well, so the greeter is right whichever of the two GDM reads.
    [/usr/share/pixmaps/fedora-gdm-logo.png]=/usr/share/pixmaps/amethystora-wordmark-glow.png
    [/usr/share/pixmaps/fedora-logo-small.png]=/usr/share/pixmaps/amethystora-wordmark-small.png
    [/usr/share/pixmaps/fedora-logo.png]=/usr/share/pixmaps/amethystora-wordmark.png
    [/usr/share/pixmaps/fedora_logo_med.png]=/usr/share/pixmaps/amethystora-wordmark-medium.png
    [/usr/share/pixmaps/fedora_whitelogo_med.png]=/usr/share/pixmaps/amethystora-wordmark-white.png
    # Settings -> About draws fedora-logo-icon.png, the path Fedora compiles into gnome-control-center
    [/usr/share/pixmaps/fedora-logo-icon.png]=/usr/share/pixmaps/amethystora-logo-512.png
    [/usr/share/pixmaps/fedora-logo-sprite.png]=/usr/share/pixmaps/amethystora-logo-400.png
    [/usr/share/pixmaps/system-logo-white.png]=/usr/share/pixmaps/amethystora-logo-white.png
    [/usr/share/icons/hicolor/scalable/places/fedora-logo-sprite.svg]=/usr/share/icons/hicolor/scalable/apps/amethystora-logo.svg
    [/usr/share/icons/hicolor/scalable/places/fedora_white_logo.svg]=/usr/share/icons/hicolor/scalable/apps/amethystora-logo.svg
    [/usr/share/icons/hicolor/scalable/places/fedora_whitelogo.svg]=/usr/share/icons/hicolor/scalable/apps/amethystora-logo.svg
    # Fedora's spinner theme is the fallback splash; its watermark.png is an Amethystora file already
    [/usr/share/plymouth/themes/spinner/silverblue-watermark.png]=/usr/share/plymouth/themes/spinner/watermark.png
)

for target in "${!UPSTREAM_ARTWORK[@]}"; do
    artwork="${UPSTREAM_ARTWORK[${target}]}"
    test -s "${artwork}"
    install -Dpm0644 "${artwork}" "${target}"
done

# Top bar: the Logo Menu draws the Amethystora gem in its own colours, not a symbolic silhouette
# that GNOME would repaint in the panel's foreground white.
#
# The extension lets its user choose the button's logo, and ships one for every distribution and
# maker it knows of: Fedora's, Red Hat's, Ubuntu's, Framework's and sixty more. A logo is a trademark
# and none of those is this image's to hand out, Fedora's least of all, which build.sh takes
# fedora-logos out for. So both of the extension's lists are cut down to its Universal Blue entry,
# whose two drawings are replaced with Amethystora's here, under the extension's file names that
# 07-debrand.sh then renames. That leaves one entry in each list, number 0: the one
# 04-amethystora-logomenu-extension and zz0-amethystora-modifications select, and the one the
# extension itself falls back to for an account whose setting names an entry that has gone.
LOGOMENU=/usr/share/gnome-shell/extensions/logomenu@aryan_k
logomenu_entries() {
    sed -n "/$1/,/^\];/p" "${LOGOMENU}/constants.js" | grep -oE "PATH: '[^']+'" | cut -d "'" -f 2
}
install -Dpm0644 /usr/share/icons/hicolor/scalable/actions/amethystora-logo-symbolic.svg \
    "${LOGOMENU}/Resources/ublue-logo-symbolic.svg"
install -Dpm0644 /usr/share/icons/hicolor/scalable/apps/amethystora-logo.svg \
    "${LOGOMENU}/Resources/ublue-logo.svg"
# The lists, with the note the GPL asks a changed file to carry: that it was changed, and when
sed -i -e "/{PATH: /{/ublue-logo/!d}" \
    -e "1i // Changed for Amethystora on $(date -u +%Y-%m-%d): the entries for other makers' logos are removed (build_files/base/06-branding.sh)" \
    "${LOGOMENU}/constants.js"
[[ "$(logomenu_entries SymbolicDistroIcons)" == "/Resources/ublue-logo-symbolic.svg" ]]
[[ "$(logomenu_entries ColouredDistroIcons)" == "/Resources/ublue-logo.svg" ]]
# The drawings, and the second copy of each that the settings window draws its chooser from. The
# picture on the extension's own About page is the one file there that is nobody's logo. The
# screenshots that come with the extension's source show the chooser with every logo in it.
find "${LOGOMENU}/Resources" -type f ! -name 'ublue-logo.svg' ! -name 'ublue-logo-symbolic.svg' \
    ! -name 'settings-logo-menu-logo.svg' -delete
[[ "$(find "${LOGOMENU}/Resources" -type f | wc -l)" == 3 ]]
rm -rf "${LOGOMENU}/screenshots"

echo "::endgroup::"
