blank_issues_enabled: true
contact_links:
  - name: Questions and Feedback
    url: https://github.com/iarsslen/amethystora/discussions
    about: Ask questions and share tips with other Amethystora users
