#!/usr/bin/bash
# Greeting shown in new terminals (/etc/profile.d/amethyst-greeting.sh, fish_greeting.fish):
# a welcome line in the Amethyst purple, then the logo and system summary.

if [ -t 1 ] && [ -z "${NO_COLOR-}" ]; then
    printf '\n\e[1;38;2;155;92;224mWelcome to Amethyst\e[0m\n\n'
else
    printf '\nWelcome to Amethyst\n\n'
fi

exec amethyst-fastfetch
